name: deploy-backend
on:
  push:
    branches: [ main ]
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps (fail fast)
        working-directory: server
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python - << 'PY'
import fastapi, uvicorn, gunicorn
print("deps ok")
PY

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: techroute-api-yggor-2
          package: ./server
