name: Deploy Python Backend to Azure App Service - techroute-api-yggor-2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Mude se a sua versão for diferente

    - name: Install dependencies into the server folder
      run: |
        python -m pip install --upgrade pip
        pip install --target="server/__pypackages__/lib/site-packages" -r server/requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'techroute-api-yggor-2'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: ./server

          

