name: Deploy Python Backend to Azure App Service - techroute-api-yggor-2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # --- PASSO CRUCIAL QUE ESTAVA FALTANDO ---
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}

    # --- PASSO DE DEPLOY QUE AGORA VAI FUNCIONAR ---
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'techroute-api-yggor-2'
        package: ./server
          


