name: Deploy Python Backend to Azure App Service - techroute-api-yggor-2

on:
  push:
    branches:
      - main
    paths:
      - 'server/**' # Só roda se houver mudanças na pasta do backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'techroute-api-yggor-2'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }} # Garanta que este é o nome do secret correto
        package: ./server

          

